### ISSUE TITLE
Produce stream from schemaless alerts

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-alert-simulator#25]
**Describe the bug**
The new Elasticc training set has been provided in the form of schemaless alerts. This means we need to provide an external schema to decode the avro files. Currently the code fails with:

```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<schedule_delays() done, defined at /home/centos/work/fink-alert-simulator/fink_alert_simulator/alertProducer.py:55> exception=UnicodeDecodeError('utf-8', b'\x8e', 0, 1, 'invalid start byte')>
Traceback (most recent call last):
  File "/home/centos/work/fink-alert-simulator/fink_alert_simulator/alertProducer.py", line 86, in schedule_delays
    yield from asyncio.ensure_future(delay(wait_time, function, arg))
  File "/home/centos/work/fink-alert-simulator/fink_alert_simulator/alertProducer.py", line 53, in delay
    return function(*args) # NOSONAR
  File "/home/centos/work/fink-alert-simulator/bin/simulate_stream.py", line 111, in send_visit
    data = avroUtils.readschemadata(file_data)
  File "/home/centos/work/fink-alert-simulator/fink_alert_simulator/avroUtils.py", line 130, in readschemadata
    message = fastavro.reader(bytes_io)
  File "fastavro/_read.pyx", line 1061, in fastavro._read.reader.__init__
  File "fastavro/_read.pyx", line 1014, in fastavro._read.file_reader.__init__
  File "fastavro/_read.pyx", line 740, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 611, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 722, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 456, in fastavro._read.read_map
  File "fastavro/_read.pyx", line 282, in fastavro._read.read_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte
^CTraceback (most recent call last):
  File "/home/centos/work/fink-alert-simulator/bin/simulate_stream.py", line 148, in <module>
    main()
  File "/home/centos/work/fink-alert-simulator/bin/simulate_stream.py", line 143, in main
    loop.run_forever()
  File "/home/centos/miniconda/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/home/centos/miniconda/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/centos/miniconda/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
```

**To Reproduce**
Try to stream new elasticc data.

**Solution**
Add a new option to enable external schema to be put.

**Comment by JulienPeloton** [comment]
#26
